-- Wellness Block B furniture packages (13 apartment types A-M) seeded from BOQ REV 8

-- Catalog products
INSERT INTO public.catalog_products (id, name, description, image_url, unit_price_eur, supplier_id, supplier_name, discipline, area, sku) VALUES
  ('prd_bb_001', 'DOUBLE BED', 'DOUBLE BED', '', 580.0, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_002', 'BEDSIDE TABLE', 'BEDSIDE TABLE', '', 152.0, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_003', 'SIDE TABLE', 'SIDE TABLE', '', 152.0, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_004', 'MIRROR', 'MIRROR & WOOD FRAME', '', 119.43, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_005', 'SOFA', 'SOFA', '', 629.71, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_006', 'CUSHIONS', 'CUSHIONS', '', 19.54, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_007', 'COFFEE TABLE (Indoor 453.82)', 'COFFEE TABLE', '', 453.82, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_008', 'POT - CERAMIC', 'POT - CERAMIC', '', 16.07, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_009', 'RUG - WOOL W2400 x L1800', 'RUG - WOOL W2400 x L1800', '', 178.23, NULL, '', 'Rugs', 'Indoor', ''),
  ('prd_bb_010', 'CONSOLE TABLE', 'CONSOLE TABLE', '', 206.28, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_011', 'POUF (108.57)', 'POUF', '', 108.57, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_012', 'DINING TABLE (346.99)', 'DINING TABLE', '', 346.99, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_013', 'DINING CHAIR (184.57)', 'DINING CHAIR', '', 184.57, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_014', 'OUTDOOR LOUNGE CHAIR (271.43)', 'OUTDOOR LOUNGE CHAIR', '', 271.43, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_015', 'CLOUD SIDE TABLE', 'CLOUD SIDE TABLE - Outdoor', '', 134.63, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_016', 'COFFEE TABLE (223.65)', 'COFFEE TABLE', '', 223.65, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_017', 'COFFEE TABLE (304.00)', 'COFFEE TABLE', '', 304.0, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_018', 'VASE - CERAMIC (37.13)', 'VASE - CERAMIC', '', 37.13, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_019', 'VASE - CERAMIC (28.45)', 'VASE - CERAMIC', '', 28.45, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_020', 'POUF UPHOLSTERED (71.66)', 'POUF UPHOLSTERED', '', 71.66, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_021', 'DINING CHAIR (141.14)', 'DINING CHAIR', '', 141.14, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_022', 'BEDSIDE TABLE (141.14)', 'BEDSIDE TABLE', '', 141.14, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_023', 'MIRROR & WOOD FRAME (178.23)', 'MIRROR & WOOD FRAME', '', 178.23, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_024', 'OUTDOOR CLOUD SIDE TABLE', 'OUTDOOR CLOUD SIDE TABLE', '', 134.63, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_025', 'POUF (112.91)', 'POUF', '', 112.91, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_026', 'DINING CHAIR (195.43)', 'DINING CHAIR', '', 195.43, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_027', 'SOFABED', 'SOFABED', '', 497.25, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_028', 'CUSHIONS (26.06)', 'CUSHIONS', '', 26.06, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_029', 'SIDE TABLE (135.02)', 'SIDE TABLE', '', 135.02, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_030', 'LOUNGE CHAIR (271.43)', 'LOUNGE CHAIR', '', 271.43, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_031', 'COFFEE TABLE (340.67)', 'COFFEE TABLE', '', 340.67, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_032', 'SIDE TABLE (271.43)', 'SIDE TABLE', '', 271.43, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_033', 'VASE CERAMIC (41.26)', 'VASE CERAMIC', '', 41.26, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_034', 'BENCH', 'BENCH', '', 195.43, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_035', 'RUG WOOL W3000 x L2000', 'RUG WOOL W3000 x L2000', '', 247.54, NULL, '', 'Rugs', 'Indoor', ''),
  ('prd_bb_036', 'VASE CERAMIC (243.85)', 'VASE CERAMIC', '', 243.85, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_037', 'VASE CERAMIC (19.76)', 'VASE CERAMIC', '', 19.76, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_038', 'DINING TABLE (597.14)', 'DINING TABLE', '', 597.14, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_039', 'SPLITTABLE BED', 'SPLITTABLE BED', '', 680.0, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_040', 'BEDROOM RUG (154.78)', 'BEDROOM RUG', '', 154.78, NULL, '', 'Rugs', 'Indoor', ''),
  ('prd_bb_041', 'OUTDOOR SOFA - ALUMINIUM FRAME, UPHOLSTERED CUSHIONS', 'OUTDOOR SOFA - ALUMINIUM FRAME, UPHOLSTERED CUSHIONS', '', 651.42, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_042', 'OUTDOOR DINING CHAIR (186.74)', 'OUTDOOR DINING CHAIR', '', 186.74, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_043', 'OUTDOOR DINING TABLE (208.45)', 'OUTDOOR DINING TABLE', '', 208.45, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_044', 'BEDSIDE TABLE (167.94)', 'BEDSIDE TABLE', '', 167.94, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_045', 'LOUNGE CHAIR (304.00)', 'LOUNGE CHAIR', '', 304.0, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_046', 'RUG (247.54)', 'RUG', '', 247.54, NULL, '', 'Rugs', 'Indoor', ''),
  ('prd_bb_047', 'VASE (29.53)', 'VASE', '', 29.53, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_048', 'BAR STOOL (173.71)', 'BAR STOOL', '', 173.71, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_049', 'BEDSIDE TABLE (148.59)', 'BEDSIDE TABLE', '', 148.59, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_050', 'OUTDOOR DINING CHAIR (147.66)', 'OUTDOOR DINING CHAIR', '', 147.66, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_051', 'OUTDOOR DINING TABLE (360.45)', 'OUTDOOR DINING TABLE', '', 360.45, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_052', 'OUTDOOR DOUBLE SOFA', 'OUTDOOR DOUBLE SOFA', '', 488.57, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_053', 'OUTDOOR LOUNGE CHAIR (282.28)', 'OUTDOOR LOUNGE CHAIR', '', 282.28, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_054', 'OUTDOOR COFFEE TABLE (232.34)', 'OUTDOOR COFFEE TABLE', '', 232.34, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_055', 'DINING TABLE CERAMIC (953.24)', 'DINING TABLE CERAMIC', '', 953.24, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_056', 'BEDROOM RUG (154.78b)', 'BEDROOM RUG', '', 154.78, NULL, '', 'Rugs', 'Indoor', ''),
  ('prd_bb_057', 'BEDSIDE TABLE (140.95)', 'BEDSIDE TABLE', '', 140.95, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_058', 'MIRROR & WOOD FRAME (168.85)', 'MIRROR & WOOD FRAME', '', 168.85, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_059', 'OUTDOOR DINING CHAIR ROPE SEAT (186.74)', 'OUTDOOR DINING CHAIR - ALUMINIUM FRAME, ROPE SEAT', '', 186.74, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_060', 'OUTDOOR DINING TABLE (360.45b)', 'OUTDOOR DINING TABLE', '', 360.45, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_061', 'COFFEE TABLE (232.34)', 'COFFEE TABLE', '', 232.34, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_062', 'OUTDOOR SUN BED', 'OUTDOOR SUN BED', '', 366.97, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_063', 'OUTDOOR SIDE TABLE (125.94)', 'OUTDOOR SIDE TABLE', '', 125.94, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_064', 'DINING TABLE CERAMIC (725.25)', 'DINING TABLE CERAMIC', '', 725.25, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_065', 'BAR STOOL (147.66)', 'BAR STOOL', '', 147.66, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_066', 'OUTDOOR DINING TABLE (699.19)', 'OUTDOOR DINING TABLE', '', 699.19, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_067', 'VASE (41.69)', 'VASE', '', 41.69, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_068', 'VASE CERAMIC (24.97)', 'VASE CERAMIC', '', 24.97, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_069', 'VASE (76.00)', 'VASE', '', 76.0, NULL, '', 'Accessories', 'Indoor', ''),
  ('prd_bb_070', 'OUTDOOR LOUNGE CHAIR SET (792.56)', 'OUTDOOR LOUNGE CHAIR - ALUMINIUM FRAME, UPHOLSTERED CUSHIONS', '', 792.56, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_071', 'OUTDOOR SUN BED (366.97)', 'OUTDOOR SUN BED', '', 366.97, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_072', 'OUTDOOR SOFA (651.42)', 'OUTDOOR SOFA', '', 651.42, NULL, '', 'Outdoor Furniture', 'Outdoor', ''),
  ('prd_bb_073', 'SIDE TABLE (203.03)', 'SIDE TABLE', '', 203.03, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_074', 'RUG (309.42)', 'RUG', '', 309.42, NULL, '', 'Rugs', 'Indoor', ''),
  ('prd_bb_075', 'BEDROOM 3-4 RUG (154.78)', 'BEDROOM 3-4 RUG', '', 154.78, NULL, '', 'Rugs', 'Indoor', ''),
  ('prd_bb_076', 'BEDROOM 3-4 SPLITTABLE BED', 'BEDROOM 3-4 SPLITTABLE BED', '', 680.0, NULL, '', 'Furniture', 'Indoor', ''),
  ('prd_bb_077', 'OUTDOOR DINING TABLE (699.19b)', 'OUTDOOR DINING TABLE', '', 699.19, NULL, '', 'Outdoor Furniture', 'Outdoor', '')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, unit_price_eur=EXCLUDED.unit_price_eur, discipline=EXCLUDED.discipline, area=EXCLUDED.area;

-- Packages
INSERT INTO public.packages (id, name, description, block, items, room_types, buildings, unit_coverage) VALUES
  ('pkg_bb_a', 'Wellness Block B — Studio Type A', 'STUDIO apartment Type A (x20 units) — Wellness Block B', 'B', '[{"productId": "prd_bb_001", "quantity": 1}, {"productId": "prd_bb_002", "quantity": 1}, {"productId": "prd_bb_003", "quantity": 1}, {"productId": "prd_bb_004", "quantity": 1}, {"productId": "prd_bb_005", "quantity": 1}, {"productId": "prd_bb_006", "quantity": 1}, {"productId": "prd_bb_007", "quantity": 1}, {"productId": "prd_bb_008", "quantity": 2}, {"productId": "prd_bb_009", "quantity": 1}, {"productId": "prd_bb_010", "quantity": 1}, {"productId": "prd_bb_011", "quantity": 1}, {"productId": "prd_bb_012", "quantity": 1}, {"productId": "prd_bb_013", "quantity": 2}, {"productId": "prd_bb_014", "quantity": 2}, {"productId": "prd_bb_015", "quantity": 1}]'::jsonb, '[]'::jsonb, '["B1","B2"]'::jsonb, '{}'::jsonb),
  ('pkg_bb_b', 'Wellness Block B — Studio Type B', 'STUDIO apartment Type B (x20 units) — Wellness Block B', 'B', '[{"productId": "prd_bb_001", "quantity": 1}, {"productId": "prd_bb_002", "quantity": 1}, {"productId": "prd_bb_003", "quantity": 1}, {"productId": "prd_bb_004", "quantity": 1}, {"productId": "prd_bb_005", "quantity": 1}, {"productId": "prd_bb_006", "quantity": 1}, {"productId": "prd_bb_016", "quantity": 1}, {"productId": "prd_bb_017", "quantity": 1}, {"productId": "prd_bb_018", "quantity": 1}, {"productId": "prd_bb_019", "quantity": 1}, {"productId": "prd_bb_009", "quantity": 1}, {"productId": "prd_bb_010", "quantity": 1}, {"productId": "prd_bb_020", "quantity": 1}, {"productId": "prd_bb_012", "quantity": 1}, {"productId": "prd_bb_021", "quantity": 2}, {"productId": "prd_bb_014", "quantity": 2}, {"productId": "prd_bb_015", "quantity": 1}]'::jsonb, '[]'::jsonb, '["B1","B2"]'::jsonb, '{}'::jsonb),
  ('pkg_bb_c', 'Wellness Block B — Studio Type C', 'STUDIO apartment Type C (x8 units) — Wellness Block B', 'B', '[{"productId": "prd_bb_001", "quantity": 1}, {"productId": "prd_bb_022", "quantity": 1}, {"productId": "prd_bb_003", "quantity": 1}, {"productId": "prd_bb_005", "quantity": 1}, {"productId": "prd_bb_006", "quantity": 1}, {"productId": "prd_bb_016", "quantity": 1}, {"productId": "prd_bb_017", "quantity": 1}, {"productId": "prd_bb_008", "quantity": 2}, {"productId": "prd_bb_004", "quantity": 1}, {"productId": "prd_bb_023", "quantity": 1}, {"productId": "prd_bb_010", "quantity": 1}, {"productId": "prd_bb_011", "quantity": 1}, {"productId": "prd_bb_012", "quantity": 1}, {"productId": "prd_bb_013", "quantity": 2}, {"productId": "prd_bb_014", "quantity": 2}, {"productId": "prd_bb_024", "quantity": 1}]'::jsonb, '[]'::jsonb, '["B1","B2"]'::jsonb, '{}'::jsonb),
  ('pkg_bb_d', 'Wellness Block B — Studio Type D', 'STUDIO apartment Type D (x8 units) — Wellness Block B', 'B', '[{"productId": "prd_bb_001", "quantity": 1}, {"productId": "prd_bb_022", "quantity": 1}, {"productId": "prd_bb_003", "quantity": 1}, {"productId": "prd_bb_005", "quantity": 1}, {"productId": "prd_bb_006", "quantity": 1}, {"productId": "prd_bb_016", "quantity": 1}, {"productId": "prd_bb_017", "quantity": 1}, {"productId": "prd_bb_018", "quantity": 1}, {"productId": "prd_bb_019", "quantity": 1}, {"productId": "prd_bb_025", "quantity": 1}, {"productId": "prd_bb_004", "quantity": 1}, {"productId": "prd_bb_023", "quantity": 1}, {"productId": "prd_bb_026", "quantity": 2}, {"productId": "prd_bb_012", "quantity": 1}, {"productId": "prd_bb_014", "quantity": 2}, {"productId": "prd_bb_024", "quantity": 1}]'::jsonb, '[]'::jsonb, '["B1","B2"]'::jsonb, '{}'::jsonb),
  ('pkg_bb_e', 'Wellness Block B — 1 Bedroom Type E', '1 BEDROOM apartment Type E (x20 units) — Wellness Block B', 'B', '[{"productId": "prd_bb_027", "quantity": 1}, {"productId": "prd_bb_028", "quantity": 1}, {"productId": "prd_bb_006", "quantity": 1}, {"productId": "prd_bb_029", "quantity": 1}, {"productId": "prd_bb_030", "quantity": 1}, {"productId": "prd_bb_031", "quantity": 1}, {"productId": "prd_bb_032", "quantity": 1}, {"productId": "prd_bb_033", "quantity": 1}, {"productId": "prd_bb_025", "quantity": 1}, {"productId": "prd_bb_010", "quantity": 1}, {"productId": "prd_bb_011", "quantity": 1}, {"productId": "prd_bb_034", "quantity": 1}, {"productId": "prd_bb_035", "quantity": 1}, {"productId": "prd_bb_036", "quantity": 1}, {"productId": "prd_bb_037", "quantity": 1}, {"productId": "prd_bb_038", "quantity": 1}, {"productId": "prd_bb_026", "quantity": 4}, {"productId": "prd_bb_039", "quantity": 1}, {"productId": "prd_bb_002", "quantity": 1}, {"productId": "prd_bb_003", "quantity": 1}, {"productId": "prd_bb_004", "quantity": 1}, {"productId": "prd_bb_040", "quantity": 1}, {"productId": "prd_bb_041", "quantity": 1}, {"productId": "prd_bb_042", "quantity": 2}, {"productId": "prd_bb_043", "quantity": 1}]'::jsonb, '[]'::jsonb, '["B1","B2"]'::jsonb, '{}'::jsonb),
  ('pkg_bb_f', 'Wellness Block B — 1 Bedroom Type F', '1 BEDROOM apartment Type F (x28 units) — Wellness Block B', 'B', '[{"productId": "prd_bb_027", "quantity": 1}, {"productId": "prd_bb_028", "quantity": 1}, {"productId": "prd_bb_006", "quantity": 1}, {"productId": "prd_bb_044", "quantity": 1}, {"productId": "prd_bb_045", "quantity": 1}, {"productId": "prd_bb_025", "quantity": 1}, {"productId": "prd_bb_016", "quantity": 1}, {"productId": "prd_bb_017", "quantity": 1}, {"productId": "prd_bb_018", "quantity": 1}, {"productId": "prd_bb_019", "quantity": 1}, {"productId": "prd_bb_034", "quantity": 1}, {"productId": "prd_bb_046", "quantity": 1}, {"productId": "prd_bb_047", "quantity": 1}, {"productId": "prd_bb_048", "quantity": 4}, {"productId": "prd_bb_039", "quantity": 1}, {"productId": "prd_bb_049", "quantity": 1}, {"productId": "prd_bb_022", "quantity": 1}, {"productId": "prd_bb_004", "quantity": 1}, {"productId": "prd_bb_040", "quantity": 1}, {"productId": "prd_bb_050", "quantity": 2}, {"productId": "prd_bb_051", "quantity": 1}, {"productId": "prd_bb_052", "quantity": 1}, {"productId": "prd_bb_053", "quantity": 1}, {"productId": "prd_bb_054", "quantity": 1}]'::jsonb, '[]'::jsonb, '["B1","B2"]'::jsonb, '{}'::jsonb),
  ('pkg_bb_g', 'Wellness Block B — 2 Bedroom Type G', '2 BEDROOM apartment Type G (x8 units) — Wellness Block B', 'B', '[{"productId": "prd_bb_027", "quantity": 1}, {"productId": "prd_bb_006", "quantity": 1}, {"productId": "prd_bb_028", "quantity": 1}, {"productId": "prd_bb_044", "quantity": 1}, {"productId": "prd_bb_020", "quantity": 1}, {"productId": "prd_bb_033", "quantity": 1}, {"productId": "prd_bb_007", "quantity": 1}, {"productId": "prd_bb_045", "quantity": 1}, {"productId": "prd_bb_034", "quantity": 1}, {"productId": "prd_bb_035", "quantity": 1}, {"productId": "prd_bb_036", "quantity": 1}, {"productId": "prd_bb_037", "quantity": 1}, {"productId": "prd_bb_055", "quantity": 1}, {"productId": "prd_bb_021", "quantity": 6}, {"productId": "prd_bb_039", "quantity": 2}, {"productId": "prd_bb_049", "quantity": 1}, {"productId": "prd_bb_002", "quantity": 1}, {"productId": "prd_bb_004", "quantity": 2}, {"productId": "prd_bb_056", "quantity": 1}, {"productId": "prd_bb_022", "quantity": 1}, {"productId": "prd_bb_057", "quantity": 1}, {"productId": "prd_bb_058", "quantity": 1}, {"productId": "prd_bb_059", "quantity": 4}, {"productId": "prd_bb_060", "quantity": 1}, {"productId": "prd_bb_014", "quantity": 2}, {"productId": "prd_bb_024", "quantity": 1}]'::jsonb, '[]'::jsonb, '["B1","B2"]'::jsonb, '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, items=EXCLUDED.items, buildings=EXCLUDED.buildings;